project:
  type: website
  render:
    - "*.qmd"
    - "!old/"
website:
  title: "Konstantinos Patelis"
  site-url: "https://www.kpatelis.com/"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Blog"
        href: blog.qmd
      - icon: github
        href: https://github.com/patelis
      - icon: twitter
        href: https://twitter.com/k_patelis
  twitter-card: true
  favicon: "assets/favicon.png"
format:
  html:
    respect-user-color-scheme: true
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css

editor: visual

